exchange: bybit
symbols: ["BTC/USDT", "ETH/USDT"]

# Bybit-supported TFs: 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 1d, 1w
timeframes: ["1m", "3m", "5m", "15m", "30m", "1h", "4h", "12h"]

lookback_bars: 800
poll_seconds: 20
discord_webhook_url: ""

impulse:
  atr_len: 14
  body_min: 0.55
  atr_mult: 1.2
  min_consecutive: 2

zones:
  max_zone_pct: 0.35

signals:
  confirm_closes: 1
  sfp_window: 3

# 🔹 New: simple trade plan settings
risk:
  retest_offset_pct: 0.03     # 0.03% beyond level for limit entry
  stop_atr_mult: 1.2          # SL = level ± ATR*mult (other side)
  tp_rr: 1.5                  # TP1 at 1.5R

dedupe_minutes: 30
