# Exchange
exchange: bybit

# Symbols to scan (added SOL)
symbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT"]

# Timeframes (Bybit-supported)
timeframes: ["1m", "3m", "5m", "15m", "30m", "1h", "4h", "12h"]

# Candles & loop
lookback_bars: 800
poll_seconds: 20

# Webhook is set on Railway as DISCORD_WEBHOOK_URL (keep blank here)
discord_webhook_url: ""

# Impulse detection
impulse:
  atr_len: 14
  body_min: 0.55
  atr_mult: 1.2
  min_consecutive: 2

# Zone settings
zones:
  max_zone_pct: 0.35

# Signal detection
signals:
  confirm_closes: 1
  sfp_window: 3

# Trade plan (for LONG/SHORT alerts)
risk:
  retest_offset_pct: 0.03
  stop_atr_mult: 1.2
  tp_rr: 1.5

# Deduping
dedupe_minutes: 30

# Debug / visibility
debug:
  log_scans: true
  log_zones: true
  heartbeat_minutes: 1
  post_debug_to_discord: false   # set to true if you want “Watching…” embeds in Discord
