exchange: bybit
symbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT"]

# Focused, high-signal TF mix
timeframes: ["1m", "5m", "15m", "1h", "4h"]

lookback_bars: 900
poll_seconds: 30            # gentler on rate limits

discord_webhook_url: ""     # keep empty; Railway env var is used

impulse:
  atr_len: 14
  body_min: 0.60            # a touch stricter = cleaner impulses
  atr_mult: 1.3
  min_consecutive: 2

zones:
  max_zone_pct: 0.30        # slightly tighter zones

signals:
  confirm_closes: 1
  sfp_window: 3

risk:
  retest_offset_pct: 0.03
  stop_atr_mult: 1.2
  tp_rr: 1.6                # nudge RR up a bit

dedupe_minutes: 30

debug:
  log_scans: true           # keep logs useful in Railway
  log_zones: false          # quieter
  heartbeat_minutes: 2
  post_debug_to_discord: false  # ✅ production: no debug posts in channel
