exchange: bybit
symbols: ["BTC/USDT", "ETH/USDT"]

# ✅ Use Bybit-supported TFs. Examples below:
# 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 1d, 1w
timeframes: ["3m", "15m", "1h"]

lookback_bars: 600
poll_seconds: 20

# leave blank in repo, set DISCORD_WEBHOOK_URL on Railway
discord_webhook_url: ""

impulse:
  atr_len: 14
  body_min: 0.55
  atr_mult: 1.2
  min_consecutive: 2

zones:
  max_zone_pct: 0.35

signals:
  confirm_closes: 1
  sfp_window: 3

dedupe_minutes: 30
