exchange: bybit
symbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT"]

timeframes: ["1m", "5m", "15m", "1h", "4h"]

lookback_bars: 900
poll_seconds: 30

discord_webhook_url: ""   # use env var

impulse:
  atr_len: 14
  body_min: 0.60
  atr_mult: 1.30
  min_consecutive: 2

zones:
  max_zone_pct: 0.30

signals:
  confirm_closes: 1
  sfp_window: 3

sfp_quality:
  min_penetration_pct: 0.02
  max_close_inside_pct: 0.02

risk:
  retest_offset_pct: 0.03
  stop_atr_mult: 1.2
  tp_rr: 1.6

filters:
  use_htf_bias: true
  htf_timeframe: "1h"
  session_filter: false
  sessions_utc: ["07:00-10:59","13:30-20:59"]

regime:
  lookback: 200
  atr_ma_len: 50
  trend_ratio_min: 1.15
  adapt_body_min: [0.55, 0.65]
  adapt_atr_mult: [1.10, 1.40]

scoring:
  w_bias: 0.30
  w_regime: 0.20
  w_zone_strength: 0.25
  w_signal_clean: 0.25
  min_score_to_alert: 55
  tf_overrides:
    "1m": 60
    "5m": 55
    "15m": 55
    "1h": 50
    "4h": 50

startup_backfill:
  enabled: true
  lookback_bars: 1500
  max_signals_per_market: 1

dedupe_minutes: 30

outcomes:
  poll_seconds: 45
  max_age_hours: 24
  miss_after_hours: 6
  tf_for_check: "1m"

debug:
  log_scans: true
  log_zones: false
  heartbeat_minutes: 2
  post_debug_to_discord: false
